### ISSUE TITLE
search have an option random

### ISSUE THREAD

**Issue by EverGasterXd** [b3yc0d3/rule34Py#15]
Hello, I have a question: why doesn't the search have an option to random, or why doesn't the random_post have an option to set a limit?
(sorry no speak  inglish)

**Comment by b3yc0d3** [comment]
First of, sorry for my late response to your question.
`random_post` doesn't have a limit parameter because it only returns one random post at a time. For a similar reason `search` doesn't has a parameter for getting random results, `search` is meant for search for posts by tags etc. and not getting random posts.

I'm open for feature ideas and requests tho.

**Comment by EverGasterXd** [comment]
hello, thanks for the answer, but I found a solution, since the objective was to search several images from the same tag in a random way.

**Comment by EverGasterXd** [comment]
hello, thanks for the answer, but I found a solution, since the objective was to search several images from the same tag in a random way.

**Comment by b3yc0d3** [comment]
No problem, i hope i could help.
